-- ====================================================================
-- SMARTDOC: Intelligent Digital Academic Document Management System
-- Complete Supabase PostgreSQL Schema (DDL) & Seed Data (DML)
-- Compatible with: PostgreSQL 14 / 15 / 16 (Supabase Cloud Database)
-- ====================================================================

-- Ensure running in public schema
SET search_path = public;

-- Drop existing tables in reverse order of foreign key dependencies
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS download_history CASCADE;
DROP TABLE IF EXISTS login_history CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS document_share_logs CASCADE;
DROP TABLE IF EXISTS document_shares CASCADE;
DROP TABLE IF EXISTS document_requests CASCADE;
DROP TABLE IF EXISTS document_verifications CASCADE;
DROP TABLE IF EXISTS document_versions CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS required_documents CASCADE;
DROP TABLE IF EXISTS document_types CASCADE;
DROP TABLE IF EXISTS document_categories CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP TABLE IF EXISTS semesters CASCADE;
DROP TABLE IF EXISTS academic_years CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- ====================================================================
-- 1. ROLES TABLE
-- ====================================================================
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 2. USERS TABLE
-- ====================================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    role_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

-- ====================================================================
-- 3. DEPARTMENTS TABLE
-- ====================================================================
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code VARCHAR(20) NOT NULL UNIQUE,
    dept_name VARCHAR(150) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 4. COURSES TABLE
-- ====================================================================
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(20) NOT NULL UNIQUE,
    course_name VARCHAR(150) NOT NULL,
    department_id BIGINT NOT NULL,
    total_semesters INT NOT NULL DEFAULT 8,
    degree_level VARCHAR(50) DEFAULT 'Undergraduate',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_department FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
);

-- ====================================================================
-- 5. ACADEMIC_YEARS TABLE
-- ====================================================================
CREATE TABLE academic_years (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_name VARCHAR(50) NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_current BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 6. SEMESTERS TABLE
-- ====================================================================
CREATE TABLE semesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_number INT NOT NULL UNIQUE,
    semester_name VARCHAR(50) NOT NULL
);

-- ====================================================================
-- 7. FACULTY TABLE
-- ====================================================================
CREATE TABLE faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    employee_code VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    department_id BIGINT NOT NULL,
    designation VARCHAR(100) NOT NULL,
    qualification VARCHAR(100),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_faculty_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_faculty_dept FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT
);

-- ====================================================================
-- 8. STUDENTS TABLE
-- ====================================================================
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    enrollment_no VARCHAR(50) NOT NULL UNIQUE,
    roll_no VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    dob DATE,
    gender VARCHAR(20),
    phone VARCHAR(20),
    department_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    current_semester_id BIGINT NOT NULL,
    assigned_faculty_id BIGINT,
    completeness_score DECIMAL(5,2) DEFAULT 0.00,
    completeness_tier VARCHAR(30) DEFAULT 'CRITICAL',
    profile_image_path VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_students_dept FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_students_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_students_year FOREIGN KEY (academic_year_id) REFERENCES academic_years (id) ON DELETE RESTRICT,
    CONSTRAINT fk_students_sem FOREIGN KEY (current_semester_id) REFERENCES semesters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_students_faculty FOREIGN KEY (assigned_faculty_id) REFERENCES faculty (id) ON DELETE SET NULL
);

-- ====================================================================
-- 9. DOCUMENT_CATEGORIES TABLE
-- ====================================================================
CREATE TABLE document_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    icon_class VARCHAR(50) DEFAULT 'bi-folder',
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ====================================================================
-- 10. DOCUMENT_TYPES TABLE
-- ====================================================================
CREATE TABLE document_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    type_code VARCHAR(50) NOT NULL UNIQUE,
    type_name VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    is_expiry_applicable BOOLEAN DEFAULT FALSE,
    default_validity_months INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_types_category FOREIGN KEY (category_id) REFERENCES document_categories (id) ON DELETE CASCADE
);

-- ====================================================================
-- 11. REQUIRED_DOCUMENTS TABLE
-- ====================================================================
CREATE TABLE required_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id BIGINT NOT NULL,
    course_id BIGINT,
    semester_id BIGINT,
    is_mandatory BOOLEAN DEFAULT TRUE,
    weightage INT DEFAULT 10,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_req_docs_type FOREIGN KEY (document_type_id) REFERENCES document_types (id) ON DELETE CASCADE,
    CONSTRAINT fk_req_docs_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_req_docs_semester FOREIGN KEY (semester_id) REFERENCES semesters (id) ON DELETE CASCADE
);

-- ====================================================================
-- 12. DOCUMENTS TABLE
-- ====================================================================
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_code VARCHAR(60) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL,
    document_type_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    current_version INT DEFAULT 1,
    status VARCHAR(50) NOT NULL DEFAULT 'UPLOADED',
    file_name VARCHAR(255) NOT NULL,
    stored_file_path VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    sha256_hash VARCHAR(64) NOT NULL,
    verification_token VARCHAR(100) UNIQUE NOT NULL,
    qr_code_path VARCHAR(500),
    issue_date DATE,
    expiry_date DATE,
    verified_at TIMESTAMP WITHOUT TIME ZONE,
    verified_by_user_id BIGINT,
    rejection_reason VARCHAR(100),
    rejection_remarks TEXT,
    is_archived BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_docs_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_docs_type FOREIGN KEY (document_type_id) REFERENCES document_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_docs_verifier FOREIGN KEY (verified_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_doc_hash ON documents (sha256_hash);
CREATE INDEX idx_doc_status ON documents (status);
CREATE INDEX idx_doc_token ON documents (verification_token);

-- ====================================================================
-- 13. DOCUMENT_VERSIONS TABLE
-- ====================================================================
CREATE TABLE document_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    stored_file_path VARCHAR(500) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    sha256_hash VARCHAR(64) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    change_summary VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_versions_doc FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_versions_uploader FOREIGN KEY (uploaded_by_user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_doc_version UNIQUE (document_id, version_number)
);

-- ====================================================================
-- 14. DOCUMENT_VERIFICATIONS TABLE
-- ====================================================================
CREATE TABLE document_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    faculty_id BIGINT,
    action VARCHAR(50) NOT NULL,
    remarks TEXT,
    reason_code VARCHAR(100),
    decision_date TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_verif_doc FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_verif_faculty FOREIGN KEY (faculty_id) REFERENCES faculty (id) ON DELETE SET NULL
);

-- ====================================================================
-- 15. DOCUMENT_REQUESTS TABLE
-- ====================================================================
CREATE TABLE document_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no VARCHAR(60) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL,
    document_type_id BIGINT NOT NULL,
    purpose VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'REQUESTED',
    admin_remarks TEXT,
    generated_document_id BIGINT,
    requested_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_doc_req_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_req_type FOREIGN KEY (document_type_id) REFERENCES document_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_doc_req_gendoc FOREIGN KEY (generated_document_id) REFERENCES documents (id) ON DELETE SET NULL
);

-- ====================================================================
-- 16. DOCUMENT_SHARES TABLE
-- ====================================================================
CREATE TABLE document_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    share_token VARCHAR(100) NOT NULL UNIQUE,
    recipient_email VARCHAR(150),
    access_passcode_hash VARCHAR(255),
    expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    max_access_count INT DEFAULT 10,
    current_access_count INT DEFAULT 0,
    is_revoked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_shares_doc FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_shares_student FOREIGN KEY (student_id) REFERENCES students (id) ON DELETE CASCADE
);

CREATE INDEX idx_share_token ON document_shares (share_token);

-- ====================================================================
-- 17. DOCUMENT_SHARE_LOGS TABLE
-- ====================================================================
CREATE TABLE document_share_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    accessed_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    access_status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_share_logs_share FOREIGN KEY (share_id) REFERENCES document_shares (id) ON DELETE CASCADE
);

-- ====================================================================
-- 18. NOTIFICATIONS TABLE
-- ====================================================================
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    link_url VARCHAR(255),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ====================================================================
-- 19. AUDIT_LOGS TABLE
-- ====================================================================
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    ip_address VARCHAR(50),
    details TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ====================================================================
-- 20. LOGIN_HISTORY TABLE
-- ====================================================================
CREATE TABLE login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    login_time TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP WITHOUT TIME ZONE,
    ip_address VARCHAR(50),
    user_agent VARCHAR(255),
    status VARCHAR(50) NOT NULL DEFAULT 'SUCCESS',
    CONSTRAINT fk_login_hist_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ====================================================================
-- 21. DOWNLOAD_HISTORY TABLE
-- ====================================================================
CREATE TABLE download_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    downloaded_by_user_id BIGINT,
    download_type VARCHAR(50) NOT NULL,
    ip_address VARCHAR(50),
    downloaded_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dl_hist_doc FOREIGN KEY (document_id) REFERENCES documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_dl_hist_user FOREIGN KEY (downloaded_by_user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- ====================================================================
-- 22. SYSTEM_SETTINGS TABLE
-- ====================================================================
CREATE TABLE system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    description VARCHAR(255),
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- ====================================================================
-- SEED DATA INSERTION
-- Password for all accounts is: password123
-- BCrypt Hash: $2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q
-- ====================================================================

-- 1. ROLES
INSERT INTO roles (id, role_name, description) VALUES
(1, 'ROLE_ADMIN', 'Institutional Administrator with full system privileges'),
(2, 'ROLE_FACULTY', 'Academic Faculty Reviewer with document verification privileges'),
(3, 'ROLE_STUDENT', 'Enrolled Student with digital locker and sharing privileges');

-- 2. USERS
INSERT INTO users (id, username, password_hash, email, role_id, is_active) VALUES
(1, 'admin', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'admin@smartdoc.edu', 1, TRUE),
(2, 'dr.sharma', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'sharma@smartdoc.edu', 2, TRUE),
(3, 'prof.patel', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'patel@smartdoc.edu', 2, TRUE),
(4, 'dr.ananya', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'ananya@smartdoc.edu', 2, TRUE),
(5, 'student.aarav', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'aarav.sharma@student.edu', 3, TRUE),
(6, 'student.diya', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'diya.verma@student.edu', 3, TRUE),
(7, 'student.rohan', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'rohan.mehta@student.edu', 3, TRUE),
(8, 'student.sneha', '$2a$10$ZcUSxd/HFEG3j.h9tMwECe17ldGTCem4HUvTs5Ki8TEd2RWDrQH3q', 'sneha.reddy@student.edu', 3, TRUE);

-- 3. DEPARTMENTS
INSERT INTO departments (id, dept_code, dept_name, description, is_active) VALUES
(1, 'CSE', 'Computer Science and Engineering', 'Department of Computing, AI and Software Systems', TRUE),
(2, 'ECE', 'Electronics and Communication Engineering', 'Department of VLSI, Embedded Systems and IoT', TRUE),
(3, 'ME', 'Mechanical Engineering', 'Department of Thermal, Robotics and Design Engineering', TRUE),
(4, 'IT', 'Information Technology', 'Department of Web and Enterprise Computing', TRUE);

-- 4. COURSES
INSERT INTO courses (id, course_code, course_name, department_id, total_semesters, degree_level, is_active) VALUES
(1, 'BTECH_CSE', 'B.Tech in Computer Science and Engineering', 1, 8, 'Undergraduate', TRUE),
(2, 'BTECH_ECE', 'B.Tech in Electronics and Communication', 2, 8, 'Undergraduate', TRUE),
(3, 'MTECH_CSE', 'M.Tech in Advanced Computer Science', 1, 4, 'Postgraduate', TRUE),
(4, 'MCA', 'Master of Computer Applications', 4, 4, 'Postgraduate', TRUE),
(5, 'BTECH_ME', 'B.Tech in Mechanical Engineering', 3, 8, 'Undergraduate', TRUE);

-- 5. ACADEMIC YEARS
INSERT INTO academic_years (id, year_name, start_date, end_date, is_current) VALUES
(1, '2022-2023', '2022-07-01', '2023-06-30', FALSE),
(2, '2023-2024', '2023-07-01', '2024-06-30', FALSE),
(3, '2024-2025', '2024-07-01', '2025-06-30', FALSE),
(4, '2025-2026', '2025-07-01', '2026-06-30', TRUE);

-- 6. SEMESTERS
INSERT INTO semesters (id, semester_number, semester_name) VALUES
(1, 1, 'Semester 1'),
(2, 2, 'Semester 2'),
(3, 3, 'Semester 3'),
(4, 4, 'Semester 4'),
(5, 5, 'Semester 5'),
(6, 6, 'Semester 6'),
(7, 7, 'Semester 7'),
(8, 8, 'Semester 8');

-- 7. FACULTY
INSERT INTO faculty (id, user_id, employee_code, first_name, last_name, phone, department_id, designation, qualification) VALUES
(1, 2, 'FAC_CSE_001', 'Dr. Ramesh', 'Sharma', '+91 98765 43210', 1, 'Professor & HOD', 'Ph.D. in Computer Science (IIT Bombay)'),
(2, 3, 'FAC_ECE_002', 'Prof. Suresh', 'Patel', '+91 98765 43211', 2, 'Associate Professor', 'M.Tech in VLSI Systems'),
(3, 4, 'FAC_CSE_003', 'Dr. Ananya', 'Gupta', '+91 98765 43212', 1, 'Assistant Professor', 'Ph.D. in Cybersecurity');

-- 8. STUDENTS
INSERT INTO students (id, user_id, enrollment_no, roll_no, first_name, last_name, dob, gender, phone, department_id, course_id, academic_year_id, current_semester_id, assigned_faculty_id, completeness_score, completeness_tier) VALUES
(1, 5, 'EN2023CSE0101', '23CSE101', 'Aarav', 'Sharma', '2004-05-15', 'Male', '+91 91234 56780', 1, 1, 4, 5, 1, 80.00, 'GOOD'),
(2, 6, 'EN2023CSE0102', '23CSE102', 'Diya', 'Verma', '2004-08-22', 'Female', '+91 91234 56781', 1, 1, 4, 5, 1, 100.00, 'EXCELLENT'),
(3, 7, 'EN2023ECE0201', '23ECE201', 'Rohan', 'Mehta', '2003-11-10', 'Male', '+91 91234 56782', 2, 2, 4, 5, 2, 40.00, 'CRITICAL'),
(4, 8, 'EN2024MCA0301', '24MCA301', 'Sneha', 'Reddy', '2002-03-30', 'Female', '+91 91234 56783', 4, 4, 4, 3, 3, 60.00, 'INCOMPLETE');

-- 9. DOCUMENT CATEGORIES
INSERT INTO document_categories (id, category_name, description, icon_class) VALUES
(1, 'IDENTITY', 'Government and Institutional Identity Documents', 'bi-person-badge'),
(2, 'ACADEMIC', 'High School, Secondary and University Academic Marksheets', 'bi-mortarboard'),
(3, 'COLLEGE', 'Admission Letters, Fee Receipts and Campus IDs', 'bi-building'),
(4, 'CERTIFICATES', 'Internships, Training, Projects and Extra-curricular Certifications', 'bi-award'),
(5, 'OTHER', 'Medical, Domicile, Caste and Miscellaneous Certificates', 'bi-folder2-open');

-- 10. DOCUMENT TYPES (Includes All Core + New Achievement & Research Types)
INSERT INTO document_types (id, category_id, type_code, type_name, description, is_expiry_applicable, default_validity_months, is_active) VALUES
(1, 1, 'AADHAAR_CARD', 'Aadhaar Card', 'Government of India National UID Card', FALSE, 0, TRUE),
(2, 1, 'PASSPORT', 'Passport', 'Official Government Issued International Passport', TRUE, 120, TRUE),
(3, 1, 'PAN_CARD', 'PAN Card', 'Income Tax Permanent Account Number Card', FALSE, 0, TRUE),
(4, 1, 'VOTER_ID', 'Voter ID Card', 'Election Commission of India Identity Card', FALSE, 0, TRUE),
(5, 2, 'MARKSHEET_10TH', '10th Standard Marksheet', 'Secondary School Examination (SSC / Matriculation)', FALSE, 0, TRUE),
(6, 2, 'MARKSHEET_12TH', '12th Standard Marksheet', 'Higher Secondary Certificate (HSC / Intermediate)', FALSE, 0, TRUE),
(7, 2, 'DIPLOMA_CERT', 'Diploma Certificate', 'Polytechnic or Technical Diploma Certificate', FALSE, 0, TRUE),
(8, 2, 'SEM_MARKSHEET', 'Semester Grade Sheet', 'University Official Semester Grade Transcript', FALSE, 0, TRUE),
(9, 2, 'PROVISIONAL_DEGREE', 'Provisional Degree Certificate', 'Provisional Graduation Certificate from Board/University', FALSE, 0, TRUE),
(10, 2, 'TRANSFER_CERT', 'Transfer Certificate (TC)', 'School / College Leaving and Transfer Certificate', FALSE, 0, TRUE),
(11, 3, 'COLLEGE_ID', 'Student College ID Card', 'Institutional Issued Student Smart ID Card', TRUE, 12, TRUE),
(12, 3, 'ADMISSION_LETTER', 'Admission Confirmation Letter', 'Official University Seat Allocation & Admission Letter', FALSE, 0, TRUE),
(13, 3, 'FEE_RECEIPT', 'Tuition Fee Receipt', 'Current Academic Year Fee Payment Proof', TRUE, 12, TRUE),
(14, 4, 'INTERNSHIP_CERT', 'Industry Internship Certificate', 'Authorized Company Internship Completion Letter', FALSE, 0, TRUE),
(15, 5, 'MEDICAL_CERT', 'Medical Fitness Certificate', 'Authorized Medical Practitioner Fitness Certificate', TRUE, 6, TRUE),
(16, 4, 'RESEARCH_PAPER', 'Research Paper / Publication', 'Journal, Conference, or IEEE/Scopus Indexed Research Paper', FALSE, 0, TRUE),
(17, 4, 'COURSE_CERT', 'Course & Skill Certification', 'Online and Offline MOOCs (Coursera, NPTEL, AWS, Cisco)', FALSE, 0, TRUE),
(18, 4, 'HACKATHON_AWARD', 'Hackathon & Coding Award', 'National and State-Level Hackathons, Coding Contests', FALSE, 0, TRUE),
(19, 4, 'WORKSHOP_CERT', 'Technical Workshop Certificate', 'Hands-on Technical Bootcamp and Seminar Participation', FALSE, 0, TRUE),
(20, 4, 'EXTRACURRICULAR_CERT', 'Extracurricular Achievement', 'Sports, Cultural, Debate, and Club Leadership Awards', FALSE, 0, TRUE),
(21, 4, 'PATENT_PUBLICATION', 'Patent / IPR Publication', 'Intellectual Property and Patent Filing or Grant', FALSE, 0, TRUE);

-- 11. REQUIRED DOCUMENTS
INSERT INTO required_documents (id, document_type_id, course_id, semester_id, is_mandatory, weightage) VALUES
(1, 1, NULL, NULL, TRUE, 20),
(2, 5, NULL, NULL, TRUE, 20),
(3, 6, NULL, NULL, TRUE, 20),
(4, 11, NULL, NULL, TRUE, 20),
(5, 12, NULL, NULL, TRUE, 20);

-- 12. SAMPLE DOCUMENTS
INSERT INTO documents (id, document_code, student_id, document_type_id, title, current_version, status, file_name, stored_file_path, file_size_bytes, mime_type, sha256_hash, verification_token, qr_code_path, issue_date, expiry_date, verified_at, verified_by_user_id, created_at) VALUES
(1, 'DOC-2026-CSE-001', 1, 1, 'Aadhaar Card - Aarav Sharma', 1, 'VERIFIED', 'aarav_aadhaar.pdf', 'storage/documents/2026/1/1/aarav_aadhaar.pdf', 1048576, 'application/pdf', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'VT-AARAV-AADHAAR-8934', 'storage/qrcodes/VT-AARAV-AADHAAR-8934.png', '2020-01-10', NULL, '2026-08-01 10:30:00', 2, '2026-08-01 09:00:00'),
(2, 'DOC-2026-CSE-002', 1, 5, '10th Board Certificate', 1, 'VERIFIED', 'aarav_10th_marks.pdf', 'storage/documents/2026/1/5/aarav_10th_marks.pdf', 2048576, 'application/pdf', 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb', 'VT-AARAV-10TH-1192', 'storage/qrcodes/VT-AARAV-10TH-1192.png', '2020-06-15', NULL, '2026-08-02 11:15:00', 2, '2026-08-01 09:10:00'),
(3, 'DOC-2026-CSE-003', 1, 6, '12th Board Certificate', 1, 'VERIFIED', 'aarav_12th_marks.pdf', 'storage/documents/2026/1/6/aarav_12th_marks.pdf', 1848576, 'application/pdf', '3e23e8160039594a33894f6564e1b1348bbd7a0088d42c4acb73eeaed59c009d', 'VT-AARAV-12TH-4481', 'storage/qrcodes/VT-AARAV-12TH-4481.png', '2022-06-20', NULL, '2026-08-02 11:20:00', 2, '2026-08-01 09:15:00'),
(4, 'DOC-2026-CSE-004', 1, 11, 'College ID Card', 1, 'VERIFIED', 'aarav_college_id.jpg', 'storage/documents/2026/1/11/aarav_college_id.jpg', 512000, 'image/jpeg', '2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6', 'VT-AARAV-COLLID-7731', 'storage/qrcodes/VT-AARAV-COLLID-7731.png', '2023-08-01', '2027-06-30', '2026-08-03 14:00:00', 2, '2026-08-01 09:20:00'),
(5, 'DOC-2026-CSE-005', 1, 12, 'Admission Offer Letter', 1, 'UNDER_REVIEW', 'aarav_admission.pdf', 'storage/documents/2026/1/12/aarav_admission.pdf', 1200000, 'application/pdf', '18ac3e7343f016890c510e93f935261169d9e3f565436429830faf093400544f', 'VT-AARAV-ADM-9921', NULL, '2023-07-15', NULL, NULL, NULL, '2026-08-10 15:30:00'),
(6, 'DOC-2026-CSE-006', 2, 1, 'Aadhaar Card - Diya Verma', 1, 'VERIFIED', 'diya_aadhaar.pdf', 'storage/documents/2026/2/1/diya_aadhaar.pdf', 950000, 'application/pdf', '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a', 'VT-DIYA-AADHAAR-3391', 'storage/qrcodes/VT-DIYA-AADHAAR-3391.png', '2020-02-12', NULL, '2026-08-05 10:00:00', 2, '2026-08-04 11:00:00'),
(7, 'DOC-2026-ECE-007', 3, 1, 'Aadhaar Card - Rohan Mehta', 1, 'REJECTED', 'rohan_aadhaar_blur.pdf', 'storage/documents/2026/3/1/rohan_aadhaar_blur.pdf', 450000, 'application/pdf', 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d', 'VT-ROHAN-AADHAAR-0012', NULL, '2020-04-01', NULL, NULL, 3, '2026-08-08 14:20:00');

UPDATE documents SET rejection_reason = 'BLURRY_UNREADABLE', rejection_remarks = 'The uploaded Aadhaar scan is blurry and UID is obscured. Please upload a clear color PDF.' WHERE id = 7;

-- 13. DOCUMENT VERSIONS
INSERT INTO document_versions (id, document_id, version_number, file_name, stored_file_path, file_size_bytes, mime_type, sha256_hash, uploaded_by_user_id, change_summary, created_at) VALUES
(1, 1, 1, 'aarav_aadhaar.pdf', 'storage/documents/2026/1/1/aarav_aadhaar.pdf', 1048576, 'application/pdf', 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 5, 'Initial verified upload', '2026-08-01 09:00:00'),
(2, 5, 1, 'aarav_admission.pdf', 'storage/documents/2026/1/12/aarav_admission.pdf', 1200000, 'application/pdf', '18ac3e7343f016890c510e93f935261169d9e3f565436429830faf093400544f', 5, 'Initial upload for review', '2026-08-10 15:30:00');

-- 14. DOCUMENT VERIFICATIONS
INSERT INTO document_verifications (id, document_id, faculty_id, action, remarks, reason_code, decision_date) VALUES
(1, 1, 1, 'APPROVED', 'Verified with original government UIDAI repository.', NULL, '2026-08-01 10:30:00'),
(2, 1, 1, 'APPROVED', 'Marksheet matches CBSE board database.', NULL, '2026-08-02 11:15:00'),
(3, 1, 1, 'APPROVED', 'Verified 12th board marksheet.', NULL, '2026-08-02 11:20:00'),
(4, 1, 1, 'APPROVED', 'Valid student college identity card.', NULL, '2026-08-03 14:00:00'),
(5, 7, 2, 'REJECTED', 'The uploaded Aadhaar scan is blurry and UID is obscured. Please upload a clear color PDF.', 'BLURRY_UNREADABLE', '2026-08-08 14:20:00');

-- 15. DOCUMENT REQUESTS
INSERT INTO document_requests (id, request_no, student_id, document_type_id, purpose, status, admin_remarks, requested_at) VALUES
(1, 'REQ-2026-00101', 1, 9, 'Required for Higher Studies / GATE Exam Application', 'PROCESSING', 'Application under review by Registrar Office', '2026-08-15 10:00:00'),
(2, 'REQ-2026-00102', 2, 10, 'Required for Education Loan Subsidy Verification', 'APPROVED', 'Certificate generated and ready for download', '2026-08-16 11:30:00');

-- 16. DOCUMENT SHARES
INSERT INTO document_shares (id, document_id, student_id, share_token, recipient_email, expires_at, max_access_count, current_access_count, is_revoked, created_at) VALUES
(1, 1, 1, 'SH-AARAV-8891238491-SEC', 'recruiter@techcorp.com', CURRENT_TIMESTAMP + INTERVAL '7 days', 10, 2, FALSE, CURRENT_TIMESTAMP);

-- 17. NOTIFICATIONS
INSERT INTO notifications (id, user_id, title, message, type, link_url, is_read, created_at) VALUES
(1, 5, 'Document Verified', 'Your 10th Standard Marksheet has been successfully verified by Dr. Ramesh Sharma.', 'VERIFICATION', '/student/vault', FALSE, CURRENT_TIMESTAMP),
(2, 5, 'Document Pending Review', 'Your Admission Offer Letter has been submitted and is currently in the faculty verification queue.', 'UPLOAD', '/student/vault', TRUE, CURRENT_TIMESTAMP),
(3, 7, 'Document Rejected', 'Your Aadhaar Card was rejected. Reason: Scan is blurry. Please upload a fresh document.', 'REJECTION', '/student/upload', FALSE, CURRENT_TIMESTAMP),
(4, 2, 'New Verification Task', 'Student Aarav Sharma has submitted Admission Offer Letter for verification.', 'UPLOAD', '/faculty/queue', FALSE, CURRENT_TIMESTAMP);

-- 18. AUDIT LOGS
INSERT INTO audit_logs (id, user_id, action, entity_type, entity_id, ip_address, details, created_at) VALUES
(1, 1, 'SYSTEM_INIT', 'SYSTEM', 1, '127.0.0.1', 'SMARTDOC Supabase Cloud Database Initialized', CURRENT_TIMESTAMP),
(2, 5, 'UPLOAD_DOC', 'DOCUMENT', 1, '192.168.1.45', 'Uploaded Aadhaar Card (DOC-2026-CSE-001)', CURRENT_TIMESTAMP),
(3, 2, 'VERIFY_DOC', 'DOCUMENT', 1, '192.168.1.10', 'Approved document DOC-2026-CSE-001 with QR code generation', CURRENT_TIMESTAMP);

-- 19. SYSTEM SETTINGS
INSERT INTO system_settings (id, setting_key, setting_value, description) VALUES
(1, 'INSTITUTE_NAME', 'National Institute of Engineering & Technology', 'Full Name of Higher Education Institution'),
(2, 'INSTITUTE_CODE', 'NIET-2026', 'Institutional Accreditation Code'),
(3, 'COMPLETENESS_CRITICAL_THRESHOLD', '50', 'Threshold below which student completeness is Critical'),
(4, 'COMPLETENESS_GOOD_THRESHOLD', '75', 'Threshold for Good completeness score'),
(5, 'COMPLETENESS_EXCELLENT_THRESHOLD', '90', 'Threshold for Excellent completeness score'),
(6, 'DEFAULT_SHARE_EXPIRY_HOURS', '48', 'Default duration for temporary secure sharing links in hours'),
(7, 'MAX_UPLOAD_SIZE_MB', '15', 'Maximum permissible file upload size in Megabytes');

-- ====================================================================
-- SYNCHRONIZE IDENTITY SEQUENCES (Prevents Primary Key collision on new inserts)
-- ====================================================================
SELECT setval(pg_get_serial_sequence('roles', 'id'), COALESCE(MAX(id), 1) + 1) FROM roles;
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1) + 1) FROM users;
SELECT setval(pg_get_serial_sequence('departments', 'id'), COALESCE(MAX(id), 1) + 1) FROM departments;
SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE(MAX(id), 1) + 1) FROM courses;
SELECT setval(pg_get_serial_sequence('academic_years', 'id'), COALESCE(MAX(id), 1) + 1) FROM academic_years;
SELECT setval(pg_get_serial_sequence('semesters', 'id'), COALESCE(MAX(id), 1) + 1) FROM semesters;
SELECT setval(pg_get_serial_sequence('faculty', 'id'), COALESCE(MAX(id), 1) + 1) FROM faculty;
SELECT setval(pg_get_serial_sequence('students', 'id'), COALESCE(MAX(id), 1) + 1) FROM students;
SELECT setval(pg_get_serial_sequence('document_categories', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_categories;
SELECT setval(pg_get_serial_sequence('document_types', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_types;
SELECT setval(pg_get_serial_sequence('required_documents', 'id'), COALESCE(MAX(id), 1) + 1) FROM required_documents;
SELECT setval(pg_get_serial_sequence('documents', 'id'), COALESCE(MAX(id), 1) + 1) FROM documents;
SELECT setval(pg_get_serial_sequence('document_versions', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_versions;
SELECT setval(pg_get_serial_sequence('document_verifications', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_verifications;
SELECT setval(pg_get_serial_sequence('document_requests', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_requests;
SELECT setval(pg_get_serial_sequence('document_shares', 'id'), COALESCE(MAX(id), 1) + 1) FROM document_shares;
SELECT setval(pg_get_serial_sequence('notifications', 'id'), COALESCE(MAX(id), 1) + 1) FROM notifications;
SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE(MAX(id), 1) + 1) FROM audit_logs;
SELECT setval(pg_get_serial_sequence('system_settings', 'id'), COALESCE(MAX(id), 1) + 1) FROM system_settings;

-- Setup completed successfully!
